// crypto-fl: cryptography primitives and wrappers
// Copyright 2026 Dark Bio AG. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

use flutter_rust_bridge::frb;

/// Derives a key of the specified length from the secret, salt, and info using HKDF-SHA256.
#[frb(sync)]
pub fn hkdf_key(secret: Vec<u8>, salt: Vec<u8>, info: Vec<u8>, length: usize) -> Vec<u8> {
    darkbio_crypto::hkdf::key_with_len(&secret, &salt, &info, length).to_vec()
}

/// Extracts a 32-byte pseudorandom key from the secret and salt using HKDF-SHA256.
/// Use this only when you need to reuse the extracted key with multiple expand calls.
#[frb(sync)]
pub fn hkdf_extract(secret: Vec<u8>, salt: Vec<u8>) -> Vec<u8> {
    darkbio_crypto::hkdf::extract(&secret, &salt).to_vec()
}

/// Expands a 32-byte pseudorandom key into a key of the specified length using HKDF-SHA256.
/// The prk should have been generated by hkdf_extract.
#[frb(sync)]
pub fn hkdf_expand(prk: Vec<u8>, info: Vec<u8>, length: usize) -> Result<Vec<u8>, String> {
    let prk_array: [u8; 32] = prk
        .try_into()
        .map_err(|_| "Invalid PRK length, expected 32 bytes".to_string())?;

    Ok(darkbio_crypto::hkdf::expand_with_len(&prk_array, &info, length).to_vec())
}
